[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "socket_pubsub"
authors = [{name = "Joseíto Oliveira", email = "joseito.oliveira@outlook.com"}]
dynamic = ["version", "description"]
